#!/usr/bin/env zsh

alias v="nvim"
alias gg="lazygit"
alias yadmauto="yadm add -u && yadm commit -m 'Auto commit' && yadm push"
alias ls='ls --color=tty --group-directories-first'
alias tree="tree -C -I 'node_modules|dist'"
alias ts="tmux-sessionizer"
alias rshada="rm -rf $HOME/AppData/Local/nvim-data/shada/* && rm -rf $HOME/.local/share/nvim/shada/*"

if command -v batcat >/dev/null 2>&1; then
    alias bat="batcat"
fi
