#!/usr/bin/env zsh

bindkey -e
bindkey -s '^f' "^Qts\n"
bindkey '^[[A' history-substring-search-up
bindkey '^[OA' history-substring-search-up
bindkey '^[[B' history-substring-search-down
bindkey '^[OB' history-substring-search-down
bindkey -M emacs '^P' history-substring-search-up
bindkey -M emacs '^N' history-substring-search-down
bindkey '^H' backward-kill-word
bindkey '5~' kill-word
