#!/usr/bin/env bash

if grep -q 0 /sys/devices/system/cpu/cpufreq/boost; then 
	echo "1" | sudo tee /sys/devices/system/cpu/cpufreq/boost
	echo "Turbo Boost enabled"
else
	echo "0" | sudo tee /sys/devices/system/cpu/cpufreq/boost
	echo "Turbo Boost disabled"
fi
