#!/usr/bin/env node

const fs = require('fs');
const child_process = require('child_process');
const readline = require('readline');

const baseUrl = 'https://uis.ptithcm.edu.vn';
const loginUrl = baseUrl + '/api/auth/login';
const getDsDiemUrl =
    baseUrl + '/api/srm/w-locdsdiemsinhvien?hien_thi_mon_theo_hkdk=false';
const svInfoUrl = baseUrl + '/api/dkmh/w-locsinhvieninfo';

const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
});

rl._writeToOutput = (s) => {
    if (!rl.stdoutMuted) return rl.output.write(s);

    if (['\r\n', '\n', '\r'].includes(s)) return rl.output.write(s);

    const question = 'Enter password: ';
    const v = s.split(question);
    if (v.length == '2') {
        rl.output.write(question);
        rl.output.write('*'.repeat(v[1].length));
    } else {
        rl.output.write('*');
    }
};

rl.question('Enter username: ', (user) => {
    rl.question('Enter password: ', (pass) => {
        rl.stdoutMuted = false;
        rl.close();
        console.log();
        main(user, pass);
    });
    rl.stdoutMuted = true;
});

async function main(username, password) {
    try {
        const loginRes = await fetch(loginUrl, {
            method: 'POST',
            body: `username=${username}&password=${password}&grant_type=password`,
        });

        if (!loginRes.ok) {
            throw new Error('Login failed');
        }

        const loginData = await loginRes.json();
        const token = loginData.access_token;

        const svInfoRes = await fetch(svInfoUrl, {
            method: 'POST',
            headers: {
                Authorization: `Bearer ${token}`,
            },
        });

        if (!svInfoRes.ok) {
            throw new Error('Get sv info failed');
        }

        const svInfoData = await svInfoRes.json();

        const dsDiemRes = await fetch(getDsDiemUrl, {
            method: 'POST',
            headers: {
                Authorization: `Bearer ${token}`,
            },
        });

        if (!dsDiemRes.ok) {
            throw new Error('Get ds diem failed');
        }

        const dsDiemData = await dsDiemRes.json();
        const htmlContent = generateHtml(
            svInfoData.data,
            dsDiemData.data.ds_diem_hocky
        );
        fs.writeFileSync('result.html', htmlContent);
        open('result.html');
    } catch (error) {
        console.error(error);
        return;
    }
}

function generateHtml(svInfo, dsDiemHocKy) {
    let html = `
        <html>
            <head>
                <title>Danh sách điểm</title>
                <style>td, th { padding: 8px; }</style>
            </head>
            <body>`;

    html += `
        <h3>Họ tên: ${svInfo.ten_day_du}</h3>
        <h3>MSSV: ${svInfo.ma_sv}</h3>
        <hr />`;

    dsDiemHocKy.forEach((hocKy) => {
        html += '<h2>' + hocKy.ten_hoc_ky + '</h2>';
        html += '<table border="1"><tr>';
        html += `
            <th>Mã môn</th>
            <th>Tên môn</th>
            <th>Số tín chỉ</th>
            <th>Điểm thi</th>
            <th>Điểm giữa kỳ</th>
            <th>Điểm tk</th>
            <th>Điểm tk số</th>
            <th>Điểm tk chữ</th>
            <th>Kết quả</th>
            <th>Điểm thành phần</th>
            `;

        html += '</tr>';
        hocKy.ds_diem_mon_hoc.forEach((monHoc) => {
            html += '<tr>';
            html += '<td>' + monHoc.ma_mon + '</td>';
            html += '<td>' + monHoc.ten_mon + '</td>';
            html += '<td>' + monHoc.so_tin_chi + '</td>';
            html += '<td>' + (monHoc.diem_thi ?? '') + '</td>';
            html += '<td>' + (monHoc.diem_giua_ky ?? '') + '</td>';
            html += '<td>' + (monHoc.diem_tk ?? '') + '</td>';
            html += '<td>' + (monHoc.diem_tk_so ?? '') + '</td>';
            html += '<td>' + (monHoc.diem_tk_chu ?? '') + '</td>';
            html += '<td>' + (monHoc.ket_qua ? 'Đạt' : 'Không đạt') + '</td>';
            html += '<td style="text-align: center;">';
            if (
                monHoc.ds_diem_thanh_phan &&
                monHoc.ds_diem_thanh_phan.length > 0
            ) {
                html += `<dialog id=${monHoc.ma_mon}>`;
                html += `<h3>${monHoc.ma_mon} - ${monHoc.ten_mon}</h3>`;

                html += `
                <table border="1" style="width: 100%">
                    <thead>
                        <tr>
                            <th>Thành phần</th>
                            <th>Trọng số</th>
                            <th>Điểm</th>
                        </tr>
                    </thead>
                    <tbody>`;

                monHoc.ds_diem_thanh_phan.forEach((tp) => {
                    html += '<tr>';
                    html += '<td>' + tp.ten_thanh_phan + '</td>';
                    html += '<td>' + tp.trong_so + '</td>';
                    html += '<td>' + tp.diem_thanh_phan + '</td>';
                    html += '</tr>';
                });
                html += '</tbody></table>';

                html += `
                        <button
                            style="margin-top: 20px"
                            onclick="document.getElementById('${monHoc.ma_mon}').close()"
                        >
                            Đóng
                        </button>`;

                html += '</dialog>';

                html += `
                    <button
                        style="
                            font-weight: bold;
                            background: none;
                            border: none;
                            cursor: pointer;
                            "
                        onclick="document.getElementById('${monHoc.ma_mon}').showModal()"
                    >
                        Chi tiết
                    </button>
                `;
            }

            html += '</td>';
        });

        html += '</tr>';
        html += '</table>';

        html += `
            <table border={1} style="margin-top: 20px; margin-bottom: 20px;">
                <tr>
                    <td>ĐTB học kỳ hệ 10: ${hocKy.dtb_hk_he10 ?? ''}</td>
                    <td>ĐTB tích luỹ hệ 10: ${hocKy.dtb_tich_luy_he_10 ?? ''}</td>
                </tr>
                <tr>
                    <td>ĐTB học kỳ hệ 4: ${hocKy.dtb_hk_he4 ?? ''}</td>
                    <td>ĐTB tích luỹ hệ 4: ${hocKy.dtb_tich_luy_he_4 ?? ''}</td>
                </tr>
                <tr>
                    <td>Số tín chỉ đạt HK: ${hocKy.so_tin_chi_dat_hk ?? ''}</td>
                    <td>
                        Số tín chỉ đạt tích luỹ: ${hocKy.so_tin_chi_dat_tich_luy ?? ''}
                    </td>
                </tr>
            </table>
        `;
    });
    html += '</body></html>';
    return html;
}

function open(path) {
    let command = '';
    switch (process.platform) {
        case 'darwin':
            command = 'open';
            break;
        case 'win32':
            command = 'start ""';
            break;
        default:
            command = 'xdg-open';
            break;
    }
    child_process.execSync(`${command} "${path}"`);
}
